person:
  name: 张三
  birthday: 2019/02/12
  pet:
    name: 小花
    age: 11
  interests:
    - 篮球
    - 足球
  score: {数学:90, 语文:90}
  salarys: [12,2334]
  allPets:
    happy:
      - name: happyPet
        age: 12
      - name: happyPet2
        age: 11
    angry:
      - name: angryPet
        age: 100